### ISSUE TITLE
Sending message with an attachment

### ISSUE THREAD

**Issue by alfwro13** [noxiii/HANotifyNextCloudTalk#13]
I am trying to figure out how to send a messages with an attachment (screenshot from frigate cctv). I am currently using Signal to handle that and the config for that is this:

```
  - service: notify.signal_cctv
    data:
      message: |
        {{ now().strftime('%H:%M %A %d %B %Y') }}

        {{ trigger.payload_json["after"]["label"] | title }} Detected on {{
        trigger.payload_json["after"]["camera"] | title }} camera
      data:
        attachments:
          - >-
            /media/frigate/clips/front_door_27-{{ trigger.payload_json["after"]["id"]}}.jpg

```

looking at the documentation I came up with this for nextcloud talk notify service:

```  - service: notify.nextcloudtalk_cctv
    data:
      message: |
        {{ now().strftime('%H:%M %A %d %B %Y') }}

        {{ trigger.payload_json["after"]["label"] | title }} Detected on {{
        trigger.payload_json["after"]["camera"] | title }} camera
      front_door_27-{{ trigger.payload_json["after"]["id"]}}.jpg:  /media/frigate/clips/front_door_27-{{ trigger.payload_json["after"]["id"]}}.jpg
```
but that is failing with error: extra keys not allowed @ data['front_door_27-1688481314.727771-xzrngi.jpg'] Where am I going wrong here? Are you able to assist?
Thanks

**Comment by noxiii** [comment]
Hey,

It should be similar like your signal example. But without the attachments but with the file nsme how it should name on nextcloud to share.



```
service: notify.nextcloudtalk
data:
  message: Text
  target:
    - name/channel
  data:
    filename.jpg: /file/path/on/hassio/filename.jpg
```


For you it should look like this:

```
service: notify.nextcloudtalk
data:
   target:
      - name/channel
   message: | {{ now().strftime('%H:%M %A %d %B %Y') }} {{ trigger.payload_json["after"]["label"] | title }} Detected on {{ trigger.payload_json["after"]["camera"] | title }} camera
   data:
      {{ trigger.payload_json["after"]["id"]}}.jpg: /media/frigate/clips/front_door_27-{{ trigger.payload_json["after"]["id"]}}.jpg 
```




I wrote it on my mobile phone. I hope that I didn't write a syntax error. But the shema shoulde be ok.
